// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLoeExoXNzbgdrx5OMbPeNtBhjmnTj4Q8',
    appId: '1:970025050149:web:88ed6fe92fbdcd2cdd5fcc',
    messagingSenderId: '970025050149',
    projectId: 'agslearn',
    authDomain: 'agslearn.firebaseapp.com',
    databaseURL: 'https://agslearn.firebaseio.com',
    storageBucket: 'agslearn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgA84IoCiOb_vVU1oWLbJkScQHptCkg8',
    appId: '1:970025050149:android:bd6daaf34c3002a4dd5fcc',
    messagingSenderId: '970025050149',
    projectId: 'agslearn',
    databaseURL: 'https://agslearn.firebaseio.com',
    storageBucket: 'agslearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZSN52N8ATnn2BXBsOV2kyf_2JqFU2XR0',
    appId: '1:970025050149:ios:b420bf97c0cfa654dd5fcc',
    messagingSenderId: '970025050149',
    projectId: 'agslearn',
    databaseURL: 'https://agslearn.firebaseio.com',
    storageBucket: 'agslearn.appspot.com',
    androidClientId: '970025050149-8ksvasjkllsmrt3jjjbjo5o12gmqlfur.apps.googleusercontent.com',
    iosClientId: '970025050149-vhtedoor0bsog7ki9bp5oqabbcm5n0bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZSN52N8ATnn2BXBsOV2kyf_2JqFU2XR0',
    appId: '1:970025050149:ios:b420bf97c0cfa654dd5fcc',
    messagingSenderId: '970025050149',
    projectId: 'agslearn',
    databaseURL: 'https://agslearn.firebaseio.com',
    storageBucket: 'agslearn.appspot.com',
    androidClientId: '970025050149-8ksvasjkllsmrt3jjjbjo5o12gmqlfur.apps.googleusercontent.com',
    iosClientId: '970025050149-vhtedoor0bsog7ki9bp5oqabbcm5n0bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLoeExoXNzbgdrx5OMbPeNtBhjmnTj4Q8',
    appId: '1:970025050149:web:6763aea191c70267dd5fcc',
    messagingSenderId: '970025050149',
    projectId: 'agslearn',
    authDomain: 'agslearn.firebaseapp.com',
    databaseURL: 'https://agslearn.firebaseio.com',
    storageBucket: 'agslearn.appspot.com',
  );

}